-- EJERCICIO PRACTICA
CREATE TABLE TALLER(
    ID_TALLER NUMBER,
    TITULO NVARCHAR2(100),
    NIVEL NUMBER,--1.BASICO 2.INTERMEDIO 3.AVANZADO
    DURACION_HRS NUMBER,
    INSTRUCTOR NUMBER, --1.ALMA 2.BRUNO 3.CECILIA 4.DAVID 5.ESTELA 6.FERNANDO
    CONSTRAINT TALLER_PK PRIMARY KEY(ID_TALLER)
);

INSERT INTO TALLER VALUES(1,'TALLER DE ORATORIA',2,10,1);
INSERT INTO TALLER VALUES(2,'INTRODUCCION A PYTHON',1,12,2);
INSERT INTO TALLER VALUES(3,'FOTOGRAFIA DIGITAL',3,15,3);
INSERT INTO TALLER VALUES(4,'DISENIO GRAFICO',NULL,18,4);
INSERT INTO TALLER VALUES(5,'MAKERTING DIGITAL',1,NULL,5);
INSERT INTO TALLER VALUES(6,'CIENCIA DE DATOS',3,18,NULL);
INSERT INTO TALLER VALUES(7,'LIDEREAZGO EFECTIVO',2,10,1);
INSERT INTO TALLER VALUES(8,NULL,NULL,NULL,NULL);
COMMIT;

--TABLA HIJO PARA PARTICIPANTES
CREATE TABLE PARTICIPANTE(
    ID_PARTICIPANTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    OCUPACION NUMBER,--1.ESTUDIANTES 2.DOCENTE 3. EMPRENDEDOR 4.PROFESIONISTA 5.EMPLEADO
    TALLER_ID NUMBER,
    CONSTRAINT PARTI_PK PRIMARY KEY(ID_PARTICIPANTE),
    CONSTRAINT PARTI_FK FOREIGN KEY(TALLER_ID) REFERENCES TALLER(ID_TALLER)
);

INSERT INTO PARTICIPANTE VALUES(1,'LUISA','CARRILLO',24,1,2);
INSERT INTO PARTICIPANTE VALUES(2,'OMAR','GOMEZ',32,3,3);
INSERT INTO PARTICIPANTE VALUES(3,'MARINA','SOLANO',28,5,6);
INSERT INTO PARTICIPANTE VALUES(4,'CARLOS','FLORES',22,1,NULL);
INSERT INTO PARTICIPANTE VALUES(5,'ANGELICA','REYES',28,4,5);
INSERT INTO PARTICIPANTE VALUES(6,'IVAN','PEREZ',35,1,1);
INSERT INTO PARTICIPANTE VALUES(7,'ALDO','MARTINEZ',30,5,3);
INSERT INTO PARTICIPANTE VALUES(8,'SANDRA','MORALES',27,NULL,6);
INSERT INTO PARTICIPANTE VALUES(9,'ROBERTO','NAVARRO',21,1,2);
INSERT INTO PARTICIPANTE VALUES(10,'LAURA','GARCIA',NULL,5,7);
INSERT INTO PARTICIPANTE VALUES(11,'SOFIA','DIAZ',25,5,NULL);
INSERT INTO PARTICIPANTE VALUES(12,'MARIO','RAMOS',29,5,NULL);
COMMIT;
SELECT * FROM PARTICIPANTE;


--1.MOSTRAR LOS REGISTROS DE LOS PARTICIPANTES JUNTO AL NOMBRE DEL TALLER, 
--USANDO CASE PARA MOSTRAR EL NOMBRE DEL INSTRUCTOR Y LA OCUPACION 
SELECT T.TITULO,T.NIVEL,T.DURACION_HRS,(
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'BRUNO'
        WHEN 3 THEN 'CECILIA'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'SIN CLASIFICACION'
        END
)AS INSTRUCTOR, 
P.ID_PARTICIPANTE, P.NOMBRE, P.APELLIDO,P.EDAD,(
    CASE OCUPACION
        WHEN 1 THEN 'ESTUDIANTES'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONISTA'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'SIN CLASIFICACION'
    END
)
AS OCUPACION
FROM TALLER T
RIGHT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID;

--2. CONTAR CUANTS PARTICIPANTES HAY POR TALLER
/*
SELECT GENERO, COUNT(ID_PELICULA) AS NO_PELICULAS FROM PELICULA
WHERE GENERO IS NOT NULL GROUP BY GENERO;
*/
SELECT T.TITULO, COUNT(P.ID_PARTICIPANTE) AS PARTICIPANTES  FROM TALLER T
RIGHT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID
GROUP BY T.TITULO;

--3.MOSTRAR LOS TALLERES CON MAYOR DURACIN Y CONCATENAR LA PALABRA HORAS AL FINAL
SELECT TITULO, CONCAT(DURACION_HRS,' HORAS.') AS DURACION
FROM TALLER WHERE DURACION_HRS = (
    SELECT MAX(DURACION_HRS) FROM TALLER
    );
--4. MOSTRAR EL NOMOBRE DEL INSTRUCTOR QUE MAS TALLERES IMPARTEN
SELECT INSTRUCTOR,
    (CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'BRUNO'
        WHEN 3 THEN 'CECILIA'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'SIN CLASIFICACION'
        END
)AS INSTRUCTOR, COUNT(*) AS TALLERES FROM TALLER GROUP BY INSTRUCTOR ORDER BY TALLERES DESC;

--5. MOSTRAR TDOS LOS INSTRUCTORES Y LA CANTIDAD DE TALLERES QUE IMPARTEN
SELECT INSTRUCTOR,
    (CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'BRUNO'
        WHEN 3 THEN 'CECILIA'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'SIN CLASIFICACION'
        END
)AS NOMBRE_INSTRUCTOR, COUNT(ID_TALLER) AS NO_TALLERES
FROM TALLER GROUP BY INSTRUCTOR ORDER BY NO_TALLERES DESC;

--6.ORDENAR LOS TALLERES ALFABETICAMENTE POR TITULO Y LUEGO POR DURACION DE MAYOR A MENOR
SELECT * FROM TALLER ORDER BY TITULO ASC, DURACION_HRS DESC;

--7.ORDENAR LOS PARTICIPANTES POR NOMBRE Y LUEGOO POOR EDAD
SELECT NOMBRE, EDAD FROM PARTICIPANTE ORDER BY NOMBRE ASC, EDAD ASC;

--8.MOSTRAR EL TOTAL DE HORAS QUE TOMARA CADA PARTICINATE SEGUN TALLER
SELECT P.NOMBRE,T.TITULO, CONCAT(T.DURACION_HRS,' HORAS')
FROM  TALLER T
LEFT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID;

--9.MOSTAR EL PARTICIPNATE CON LA MAYOR CANTIDA DE HORAS POR TOMAR
SELECT P.NOMBRE, T.DURACION_HRS
FROM  TALLER T
LEFT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID
WHERE T.DURACION_HRS = (
SELECT MAX(T.DURACION_HRS) FROM TALLER T
);

--10.MOSTRAR LOS PARTICIPANTES QUE NO TIENEN TALLER ASIGNADO JUNTO CON SU CASE DE OCUPACION
SELECT T.TITULO,P.NOMBRE,
(
    CASE OCUPACION
        WHEN 1 THEN 'ESTUDIANTES'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONISTA'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'SIN CLASIFICACION'
    END
) AS OCUPACION_
FROM TALLER T
RIGHT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID
WHERE T.ID_TALLER IS NULL;

--11.MOSTRA LOS TALLERES QUE N HA SIDO ASIGNADOS A NINGUN PARTICIPANTE Y SU CASE DE INSTRUCTOR
SELECT T.TITULO,(
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'BRUNO'
        WHEN 3 THEN 'CECILIA'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'SIN CLASIFICACION'
        END
) AS NOMBRE_INST, P.ID_PARTICIPANTE,P.NOMBRE FROM TALLER T
LEFT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID
WHERE P.TALLER_ID IS NULL;


--12.. MOSTRAR LOS DETALLES DE CADA PARTICIPANTE CON LOS DATOS DEL TALLER AL QUE ASTETTRA USANDO CASE Y CONCAT O || 

SELECT     
    P.NOMBRE||' '||P.APELLIDO||' '||P.EDAD||' ANIOS'||' '||(
        CASE OCUPACION
        WHEN 1 THEN 'ESTUDIANTES'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONISTA'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'SIN CLASIFICACION'
    END
    )||' ' ||'TALLER: '||
     T.TITULO||' '||'NIVEL: '|| T.NIVEL||' '||T.DURACION_HRS||' HORAS.'||' '||'INSTRUCTOR: '||(
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'BRUNO'
        WHEN 3 THEN 'CECILIA'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'SIN CLASIFICACION'
        END
) AS NOMBRE_INST
FROM TALLER T
RIGHT JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID;







