--ACTIVIDAD DE PRACTICA CON SETENCIA CASE
DROP TABLE PRODUCTO;
--TABLA PRODUCTO
CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(100),
    CATEGORIA_ID NUMBER, --1.TECNOLOGIA 2.HOGAR 3.ROPA 4.JUGUETERIA 5.FARMACIA
    PRECIO NUMBER,
    STOCK NUMBER,
    MARCA NVARCHAR2(100),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO)
);
COMMIT;

--1.AGREGAR POR LOS MENOS 10 REGISTROS, USANDO TAMBIEN VALORES NULOS
INSERT INTO PRODUCTO VALUES(1,'NINTENDO SWITCH',1,8000.00,NULL,'NITENDO');
INSERT INTO PRODUCTO VALUES(2,'IMPRESORA HP',1,5000.70,10,'HP');
INSERT INTO PRODUCTO VALUES(3,'JUEGO SARTENES',2,1000.00,20,'T-FAL');
INSERT INTO PRODUCTO VALUES(4,'ASADOR DE CARBON',2,2999.00,NULL,'WEBER');
INSERT INTO PRODUCTO VALUES(5,'PIJAMA JUVENIL',3,159.00,15,'LOVEST');
INSERT INTO PRODUCTO VALUES(6,'VESTIDO',3,NULL,0,'DEVENDI');
INSERT INTO PRODUCTO VALUES(7,'MI AMIGO PUG',4,500.00,15,'WINFUN');
INSERT INTO PRODUCTO VALUES(8,'PILA DE ARITOS',4,NULL,NULL,'FISHER PRICE');
INSERT INTO PRODUCTO VALUES(9,'DICLOFENACO',5,140.00,50,'VOLTAREN');
INSERT INTO PRODUCTO VALUES(10,'SUSPENSION',5,412.25,NULL,'SINUBERASE');
COMMIT;

--2.MOSTRAR EL NOMBRE DE LA CATEGORIA USANDO LA SENTENCIA CASE
SELECT ID_PRODUCTO, NOMBRE,
(
    CASE CATEGORIA_ID
    WHEN 1 THEN 'TECNOLOGIA'
    WHEN 2 THEN 'HOGAR'
    WHEN 3 THEN 'ROPA'
    WHEN 4 THEN 'JUGUETERIA'
    WHEN 5 THEN 'FARMACIA'
    ELSE 'NO CLASIFICADO'    
    END
) AS CATEGORIA, PRECIO, STOCK, MARCA FROM PRODUCTO; 



--3.CLASIFICAR PRODUCTOS SEGUN EL PRECIO(CARO, MEDIO, ECONOMICO, NO CLASIFICACO)

SELECT ID_PRODUCTO, NOMBRE, CATEGORIA_ID,PRECIO,
(
    CASE
    WHEN PRECIO >= 3000 THEN 'ES CARO: '||TO_CHAR(PRECIO, '$9,999.00') ||' PESOS'
    WHEN (PRECIO >= 1000 AND PRECIO <3000) THEN 'ES MEDIO: '||TO_CHAR(PRECIO, '$9,999.00') ||' PESOS'
    WHEN PRECIO < 1000 THEN 'ES ECONOMICO: '||TO_CHAR(PRECIO, '$9,999.00') ||' PESOS'
    ELSE 'PRECIO NO DEFINIDO'
    END
)AS PRECIO_, STOCK, MARCA FROM PRODUCTO;

--4.CLASIFICAR PRODUCTOS POR DISPONIBILIDAD DE STOCK (AGOTADO, BAJO STOCK, STOCK SUFICIENTE, STOCK ABUNDANTE)
--5.CREAR UN MENSAJE CON CASE (STOCK EN 0, DIRA PRODUCTO 'AGOTADO')
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA_ID, PRECIO,
(
    CASE
    WHEN STOCK = 0 THEN 'AGOTADO'
    WHEN STOCK BETWEEN 1 AND 10 THEN 'BAJO STOCK'
    WHEN STOCK BETWEEN 11 AND 40 THEN 'SUFICIENTE STOCK'
    WHEN STOCK >= 50 THEN 'ABUNDANTE STOCK'
    ELSE 'NO CLASIFICADO'
    END
) AS STOCK, MARCA FROM PRODUCTO;

--5.CREAR UN MENSAJE CON CASE (STOCK EN 0, DIRA PRODUCTO 'AGOTADO')
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA_ID, PRECIO, STOCK,
    CASE 
    WHEN STOCK = 0 THEN 'PRODUCTO AGOTADO'
    ELSE 'DISPONIBLE'
    END 
AS ESTADO_STOCK, MARCA FROM PRODUCTO;


--6.USA EL CASE CON MAS DE UNA CONDICION (PRECIO Y STOCK) EJEMPLO 'OFERTA EN ABUNDANCIA'
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA_ID,PRECIO,
(
    CASE
    WHEN PRECIO < 1000 AND STOCK > 50 THEN 'OFERTA EN ABUNDANCIA'
    WHEN PRECIO <= 1000 AND STOCK BETWEEN 1 AND 50 THEN 'OFERTA LIMITADA'
    WHEN PRECIO >= 3000 AND STOCK > 0 THEN 'PRODUCTO DISPONIBLE'
    WHEN STOCK = 0 THEN 'PRODUCTO AGOTADO'
    ELSE 'SIN CLASIFICACION'
    END
)AS OFERTAS,STOCK,MARCA FROM PRODUCTO;


--7.

