--Ejercicio con sentencia CASE

/*
WHEN CONDICION1 THEN RESULTADO1
WHEN CONDICION2 THEN RESULTADO2
...
ELSE RESULTADO_PREDETERMINADO
END
*/

--CREAR UN DDL DE LA ENTIDAD LIBRO
CREATE TABLE LIBRO(
    ID_LIBRO NUMBER,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    GENERO NUMBER, -- 1.DRAMA,2.TERROR,3.CIENCIA FICCION,4.NOVELA,5.THIRLLER,6.COMEDIA
    NO_PAGINAS NUMBER,
    PRECIO NUMBER,
    EDITORIAL NVARCHAR2(100),
    CONSTRAINT LIBRO_PK PRIMARY KEY (ID_LIBRO)
    
);
DROP TABLE LIBRO;

INSERT INTO LIBRO VALUES(1,'CIEN ANIOS DE SOLEDAD','GABRIEL GAARCIA MARQUEZ',4,417,299.99,'SUDAMERICANA');
INSERT INTO LIBRO VALUES(2,'IT','STEPHEM KING',2,1138,399.50,'VIKING PRESS');
INSERT INTO LIBRO VALUES(3,'1984','GEROGE ORWELL',3,324,NULL,'SECKER Y WARBUR');
INSERT INTO LIBRO VALUES(4,'EL DIARIO DE ANA FRANK','ANA FRANK',0,0,NULL,'CONTACT PUBLISH');
INSERT INTO LIBRO VALUES(5,'EL CODIGO DA VINCI','DAN BRONWN',5,454,329.00,NULL);
INSERT INTO LIBRO VALUES(6,'DON QUIJOTE DE LA MANCHA','MIGUEL CERVANTES',4,863,349.99,'FRANC');
INSERT INTO LIBRO VALUES(7,'EL MARCIANO',NULL,3,0,NULL,NULL);
INSERT INTO LIBRO VALUES(8,'LOS JUEGOS DEL HAMBRE','SUZANNE COLLINS',3,347,310,'SCHOLASTIC');
INSERT INTO LIBRO VALUES(9,'LOS HOMBRES QUE NO AMABAN A LAS MUJERES',NULL,5,672,900,'NORTSTEDST');
INSERT INTO LIBRO VALUES(10,NULL,'EDUARDO MENDOOZA',0,0,NULL,NULL);

COMMIT; 


SELECT ID_LIBRO, NOMBRE, AUTOR,
(
    CASE GENERO
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'CIENCIA FICCION'
    WHEN 4 THEN 'NOVELA'
    WHEN 5 THEN 'THRILLER'
    WHEN 6 THEN 'COMEDIA'
    ELSE 'SIN GENERO'
    END
) AS GENERO, NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;

--
SELECT ID_LIBRO,NOMBRE, AUTOR, GENERO, NO_PAGINAS,
(
    CASE
        WHEN PRECIO > 400 THEN ' ES CARO: '||TO_CHAR(PRECIO, '$9,999.00') ||'PESOS'
        WHEN PRECIO <= 400 THEN ' ES BARATO: '||TO_CHAR(PRECIO, '$9,9990.00') ||'PESOS'
        ELSE 'PRECIO NO DEFINIDO'
        END
) AS PRECIO , EDITORIAL FROM LIBRO;


--






