--ejercicio de practica de joins
--TABLA PADRE PROFESOR
CREATE TABLE PROFESOR(
    ID_PROFESOR NUMBER,
    NOMBRE NVARCHAR2(100),
    ESPECIALIDAD NVARCHAR2(100),
    ANTIGUEDAD NUMBER,
    CONSTRAINT PROFESOR_PK PRIMARY KEY (ID_PROFESOR)
);

INSERT INTO PROFESOR VALUES(1,'ALICIA','MATEMATICAS',10);
INSERT INTO PROFESOR VALUES(2,'FERNANDO','HISTORIA',7);
INSERT INTO PROFESOR VALUES(3,'BEATRIZ',NULL,5);
INSERT INTO PROFESOR VALUES(4,'JORGUE','FISICA',NULL);
INSERT INTO PROFESOR VALUES(5,NULL,NULL,NULL);
INSERT INTO PROFESOR VALUES(6,'GLORIA','QUIMICA',15);

--TABLA HIJO PARA CURSO
CREATE TABLE CURSO(
    ID_CURSO NUMBER,
    NOMBRE NVARCHAR2(100),
    NIVEL NVARCHAR2(100),
    PROFESOR_ID NUMBER,
    CONSTRAINT CURSO_PK PRIMARY KEY(ID_CURSO),
    CONSTRAINT PROFESOR_FK FOREIGN KEY(PROFESOR_ID) REFERENCES PROFESOR(ID_PROFESOR) 
);

INSERT INTO CURSO VALUES(1,'ALGEBRA','AVANZADO',1);
INSERT INTO CURSO VALUES(2,'HISTORIA MODERNA','INTERMEDIO',2);
INSERT INTO CURSO VALUES(3,'FISICA CUANTICA','AVANZADO',NULL);
INSERT INTO CURSO VALUES(4,'LOGICA MATEMATICA','BASICO',1);
INSERT INTO CURSO VALUES(5,'INTRODUCCION A LA QUIMICA','BASICO',6);
INSERT INTO CURSO VALUES(6,'CIENCIAS SOCIALES','INTERMEDIO',NULL);

SELECT * FROM PROFESOR;
SELECT * FROM CURSO;

--1.CURSOS QUE TIENEN PROFESOR ASIGNADO
SELECT * FROM CURSO C
INNER JOIN PROFESOR P
ON C.PROFESOR_ID = P.ID_PROFESOR;


--2.TODS LOS CURSOS, AUNQUE NO TENGA PROFESOR ASIGNADO
SELECT * FROM CURSO C 
LEFT JOIN PROFESOR P
ON C.PROFESOR_ID = P.ID_PROFESOR;

--3.CURSOS SIN PROFESOR ASIGNADO
SELECT * FROM CURSO C 
LEFT JOIN PROFESOR P
ON C.PROFESOR_ID = P.ID_PROFESOR
WHERE P.ID_PROFESOR IS NULL;


--4.TODOS LOS PROFESORES AUNQUE NO DEN CURSOS

SELECT * FROM CURSO C
RIGHT JOIN PROFESOR P
ON C.PROFESOR_ID = P.ID_PROFESOR;

--5.PROFESORES SIN CURSO ASIGNADO
SELECT * FROM CURSO C
RIGHT JOIN PROFESOR P
ON C.PROFESOR_ID = P.ID_PROFESOR
WHERE C.PROFESOR_ID IS NULL;

--6.TODOS LOS PROFESORES Y CURSOS
SELECT * FROM CURSO C
FULL JOIN PROFESOR P
ON C.PROFESOR_ID =  P.ID_PROFESOR;

--7.PROFESORES SIN CURSOS Y TODOS LOS CURSOS SIN PROFESOR
SELECT * FROM CURSO C
FULL JOIN PROFESOR P
ON C.PROFESOR_ID =  P.ID_PROFESOR
WHERE C.PROFESOR_ID IS NULL
OR P.ID_PROFESOR IS NULL;









