--EJERCICIO DE JOINS

--CREAR TABLA PADRE
CREATE TABLE PADRE(
    ID_PADRE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    TRABAJO NVARCHAR2(100),
    CONSTRAINT PDRE_PK PRIMARY KEY (ID_PADRE)
);


INSERT INTO PADRE VALUES(1,'BRAULIO','GRAJALES',56,'DOCENTE');
INSERT INTO PADRE VALUES(2,'MEGAN','CASTILLO',NULL,NULL);
INSERT INTO PADRE VALUES(3,'EDUARDO','HERNANDEZ',50,'CONTADOR');
INSERT INTO PADRE VALUES(4,NULL,'FERNANDEZ',30,'CHEF');
INSERT INTO PADRE VALUES(5,'CARLOS',NULL,23,'MECANICO');
INSERT INTO PADRE VALUES(6,'DAMIAN',NULL,NULL,NULL);
INSERT INTO PADRE VALUES(7,'PEDRO','PEREZ',40,'INGENIERO');
INSERT INTO PADRE VALUES(8,'LAURA','LOPEZ',29,'CONTADORA');

--CREAR TABLA
CREATE TABLE HIJO(
    ID_HIJO NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    HOBBIE NVARCHAR2(100),
    PADRE_ID NUMBER,
    CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
    CONSTRAINT PADRE_FK FOREIGN KEY(PADRE_ID) REFERENCES PADRE(ID_PADRE)
    --
    
);
INSERT INTO HIJO VALUES(1,'MARIANA','GRAJALES',19,'BAILAR',1);
INSERT INTO HIJO VALUES(2,'DANIELA','MENDEZ',5,'JUGAR CON BARBIES',NULL);
INSERT INTO HIJO VALUES(3,'JOSE','HERNANDEZ',8,'JUGAR XBOX',3);
INSERT INTO HIJO VALUES(4,'LILIANA','MONTALVO',16,'LEER',NULL);
INSERT INTO HIJO VALUES(5,'LOURDES','CASTILLO',4,'VER CARICATURAS',5);
INSERT INTO HIJO VALUES(6,'HECTOR','CASTILLO',8,'AJEDREZ',5);
INSERT INTO HIJO VALUES(7,'JULIA','PEREZ',13,'NADAR',7);
INSERT INTO HIJO VALUES(8,'DALILA','PEREZ',17,'ESCRIBIR POEMAS',7);


--USO DE LOS JOINS

--INNER JOIN: DEVUELVE REGISTROS QUE TIENEN VALORES COINCIDENTES EN AMBAS TABLAS
--
SELECT * FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--LEFT JOIN: DEVUELVE TODOS LOS REGISTROS DE LA TABLA IZQUIERDA(HIJO) Y LOS REGISTROS
--COINCIDENTES CON LA TABLE DERECHA8(PADRE)
SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--LEFT JOIN QUITANDO COINCIDENCIAS
SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--RIGHT JOIN: DEVUELVE TODOS LOS REGISTROS DE LA TABLA DERECHA(PADRE) Y LOS REGISTROS COINCIDENTES
--CON LAS TABLA IZQUIERDA(HIJO)

SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--RIGHT JOIN SIN COINCIDENCIAS
SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--FULL JOIN: DEVUELVE TDOS LOS REGISTROS Y LAS COINCIDENCIAS
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--FULL JOIN SIN COINCIDENCIAS
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE 
WHERE H.PADRE_ID IS NULL 
OR P.ID_PADRE IS NULL;


