--Modificar la sesion actual para la ejecucion de scripts
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CREACION DE UN NUEVO USUARIO Y CON PASSWORD
CREATE USER ADMIN1 IDENTIFIED BY 12345;

--OTORGAR TODOS LOS PRIVILEGIOS
GRANT ALL PRIVILEGES TO ADMIN1;