--PROCEDIMIENTO ALMACENADO

/*
1. Encabezado (CREATE OR REPLACE PROCEDURE)
OR REPLACE: Permite modificar el procedimiento si ya existe.

Parámetros:

IN (entrada, valor por defecto).

OUT (salida, para devolver valores).

IN OUT (entrada y salida).

2. Sección IS (Declaraciones)
Variables locales y cursores.

3. Cuerpo (BEGIN ... END)
Contiene la lógica SQL y PL/SQL.

4. Manejo de Excepciones (EXCEPTION)
Opcional, para controlar errores.
****************************

CREATE [OR REPLACE] PROCEDURE nombre_procedimiento (
    parametro1 [IN|OUT|IN OUT] tipo_dato,
    parametro2 [IN|OUT|IN OUT] tipo_dato,
    ...
)
IS
    -- Declaración de variables locales
BEGIN
    -- Cuerpo del procedimiento (lógica)
EXCEPTION
    -- Manejo de excepciones (opcional)
END nombre_procedimiento;
*/

--CREAR UN DDL
CREATE TABLE COMPUTADORA_PRD(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPU)

);
COMMIT;

INSERT INTO COMPUTADORA VALUES(1,'ASUS','ROG STRIX',16,'INTEL CORE i7 12TH',15000);
INSERT INTO COMPUTADORA VALUES(2,'LENOVO','THINK PAD',16,'INTEL CORE i7',22000);
INSERT INTO COMPUTADORA VALUES(3,'DELL','INSPIRION',16,'INTEL CORE i9',19000);
INSERT INTO COMPUTADORA VALUES(4,'HP','PAVILON',8,'CELERON',5000);
INSERT INTO COMPUTADORA VALUES(5,'ACER','NITRO V',8,'INTEL CORA i5',10000);
INSERT INTO COMPUTADORA VALUES(6,'MACBOOK','PRO 24',16,'M4',24000);
--INSERT INTO COMPUTADORA VALUES(7,'ASUS','ROG STRIX',16,'INTEL CORE 17 12TH',15000);

DROP TABLE COMPUTADORA;

--SENTENCIA INSERT INTO SELECT
CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS--LAS DECLARACIONES DE VARIABLES, CONSTANTES O CURSORES
BEGIN
    --INSTRUCCIONES A EJECUTAR
    
    DELETE FROM COMPUTADORA_PRD;
    
    --REALIZAR RESPALDO DE MMMI COMPUTADORA
    INSERT INTO COMPUTADORA_PRD(ID_COMPU,MARCA, MODELO,RAM, PROCESADOR,PRECIO)
        SELECT ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO FROM COMPUTADORA;
END;
/
    
SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;

EXECUTE PR_RESPALDO_COMPUTADORA;

--REALIZAR UN PA PARA RESPALDAR LA ENTIDAD DE SU EJERCICI0
CREATE TABLE PERSONA_PRD(
    ID_PERSONA NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO_P NVARCHAR2(100),
    APELLIDO_M NVARCHAR2(100),
    EDAD NUMBER,
    CORREO NVARCHAR2(100),
    CONSTRAINT PERSONA_PRD_PK PRIMARY KEY(ID_PERSONA)
);

COMMIT;

INSERT INTO PERSONA VALUES(1,'NORMA','ROMERO','ROMERO',35,'NORMA@GMAIL.COM');
INSERT INTO PERSONA VALUES(2,'MITZY','ZAMUDIO','LIMA',24,'MITZY@GMAIL.COM');
INSERT INTO PERSONA VALUES(3,'ALE','ARREOLA','GARFIAS',30,'ALE@GMAIL.COM');
INSERT INTO PERSONA VALUES(4,'ALEXIS','VARGAS','LLOSA',27,'ALEXIS@GMAIL.COM');
INSERT INTO PERSONA VALUES(5,'PAUL','PEREZ','LOPEZ',40,'PAUL@GMAIL.COM');
INSERT INTO PERSONA VALUES(6,'SONIA','LOPEZ','MENDEZ',15,'SONIA@GMAIL.COM');
INSERT INTO PERSONA VALUES(7,'LUPE','ROBLES','CANALES',32,'LUPE@GMAIL.COM');


--REALIZAR UN TIPO DE RESPALDO DE INFORMACIOON PARA LA TABLA PERSONA
--SENTENCIA INSERT INTO SELECT
CREATE OR REPLACE PROCEDURE PR_RESPALDO_PERSONA
IS--LAS DECLARACIONES DE VARIABLES, CONSTANTES O CURSORES
BEGIN
    --INSTRUCCIONES A EJECUTAR
    --ELIMINAR TODO DE MI TABLA PERSONA_PRD(LIMPIAR LA TABLA)
    DELETE FROM PERSONA_PRD;
    
    --REALIZAR RESPALDO DE MI COMPUTADORA EN MI PERSONA_PRD
    INSERT INTO PERSONA_PRD(ID_PERSONA,NOMBRE,APELLIDO_P,APELLIDO_M,EDAD,CORREO)
        SELECT ID_PERSONA,NOMBRE,APELLIDO_P,APELLIDO_M,EDAD,CORREO FROM PERSONA;
END;
/

--CON EXECUTE SE EJECUTA EL PROCESO ALMACENADO
EXECUTE PR_RESPALDO_PERSONA;



SELECT * FROM PERSONA;
SELECT * FROM PERSONA_PRD;

DELETE FROM PERSONA WHERE ID_PERSONA = 2;
