--VISTAS O VIEWS: ES UNA ALTERNATIVA PARA VISUALIZAR LOS DATOS O MAS TABLAS CREANDO UNA TABLA VIRTUAL

SELECT *FROM PADRE;
SELECT * FROM HIJO;

--CREACION DE UNA VISTA
CREATE OR REPLACE VIEW V_PADRE_HIJO_DETALLE
AS
SELECT H.ID_HIJO, H.NOMBRE,H.APELLIDO,H.EDAD,NVL(H.HOBBIE,'SIN NOMBRE')AS HOBBIE, NVL(H.PADRE_ID,0) AS
PADRE FROM HIJO H LEFT JOIN PADRE P ON H.PADRE_ID = P.ID_PADRE;
--EL VIEW NO ES NECESARIO CERRARLO

SELECT * FROM V_PADRE_HIJO_DETALLE;

--CREAR UNA VISTA 

SELECT * FROM TALLER;
SELECT * FROM PARTICIPANTE;
CREATE OR REPLACE VIEW V_TALLER_PARTIC_DETALLE
AS
SELECT
T.TITULO,NVL(T.NIVEL,0)AS NIVEL,NVL(T.DURACION_HRS,0) AS DURACION,(
    CASE T.INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'BRUNO'
        WHEN 3 THEN 'CECILIA'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'SIN CLASIFICACION'
        END
)AS NOMBRE_INSTRUCTOR, 
P.ID_PARTICIPANTE,P.NOMBRE,P.APELLIDO,NVL(P.EDAD,0) AS EDAD,
(
    CASE P.OCUPACION
        WHEN 1 THEN 'ESTUDIANTES'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONISTA'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'SIN CLASIFICACION'
    END
)
AS OCUPACION,NVL(P.TALLER_ID,0) AS TALLER
FROM TALLER T INNER JOIN PARTICIPANTE P
ON T.ID_TALLER = P.TALLER_ID;

SELECT * FROM V_TALLER_PARTIC_DETALLE;


