--PACKAGE: NOS SIRVE PARA ALMACENAR PROCEDIMIENTOS, CURSORES, FUNCIOONES, Y CONSULTAS

--CREAR LA CABECERA DEL PAQUETE
CREATE OR REPLACE PACKAGE PKG_GENERAL AS
    --ALMACENAR NUESTRA FUNCION
    FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
    RETURN NVARCHAR2;
    
    --ALMACENAR EL PROCEDIMIENTO CON CURSOR
    PROCEDURE PR_DETALLE_LIBRO;
END;
/

--DECLARACION DEL BODY DEL PACKAGE
CREATE OR REPLACE PACKAGE BODY PKG_GENERAL AS

FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER ) RETURN NVARCHAR2
IS
LV_RESULTADO NVARCHAR2(100);
BEGIN 
    --SABER SI EL NUMERO ES PAR
    IF MOD(P_NUMERO,2) = 0 THEN
        LV_RESULTADO := 'EL NUMERO '||P_NUMERO||' ES PAR';
    ELSE
         LV_RESULTADO := 'EL NUMERO '||P_NUMERO||' NO ES PAR';
    END IF;
    RETURN LV_RESULTADO;

END FN_NUMERO_PAR;

---CURSOR
PROCEDURE PR_DETALLE_LIBRO
IS 
    --CURSOR
    CURSOR LIBRO_INFO IS
        SELECT NOMBRE,
        (CASE GENERO
            WHEN 1 THEN 'DRAMA'
            WHEN 2 THEN 'TERROR'
            WHEN 3 THEN 'CIENCIA FICCION'
            WHEN 4 THEN 'NOVELA'
            WHEN 5 THEN 'THILLER'
            WHEN 6 THEN 'COMEDIA'
            ELSE 'SIN GENERO'
        END
        ) AS GENERO, PRECIO FROM LIBRO;
        
        LV_NOMBRE LIBRO.NOMBRE%TYPE;
        LV_GENERO NVARCHAR2(100);
        LV_PRECIO NUMBER;
BEGIN
    --
    OPEN LIBRO_INFO;
        LOOP
        FETCH LIBRO_INFO INTO LV_NOMBRE,LV_GENERO,LV_PRECIO;
    EXIT WHEN LIBRO_INFO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('EL LIBRO '||LV_NOMBRE||' GENERO '||LV_GENERO||' CUESTA '||LV_PRECIO);
    END LOOP;
    CLOSE LIBRO_INFO;
    END PR_DETALLE_LIBRO;
END PKG_GENERAL;
/
    
    
        

--INVOCAR CURSOR
BEGIN 
    PKG_GENERAL.PR_DETALLE_LIBRO;
END;