    
--Modificar la sesion actual para la ejecucion de scripts
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CREACION DE UN NUEVO USUARIO Y CON PASSWORD
CREATE USER NBA IDENTIFIED BY NBA2025;

--OTORGAR TODOS LOS PRIVILEGIOS
GRANT ALL PRIVILEGES TO NBA;
