--TRIGGER SIMPLE O DISPARADOR: ES UN BLOQUE DE CODIGO ASOCIADO A UNA TABLA PARA
--REGISTRAR LOS MOVIMIENTOS DE TIPO DML

--DDL PARA LA ENTIDAD COMPUTADORA
CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);
COMMIT;

--DDL PARA LA ENTIDAD BITACORA DE COMPUTADORA QUE REGISTRARA CADA MOVIMIENTO EN LA TABLA COMPUTADORA
CREATE TABLE BIT_COMPUTADORA(
    ID_BIT NUMBER,--PK DE BITACORA
    
    --VALORES NUEVOS O VALORES :NEW
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    
    --VALORES ELIMINADOS O VALORES :OLD
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    --
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY(ID_BIT)
    
);
--TRIGGER SIMPLE PARA INSERTAR VALORES
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW 
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FECHA DATE;
BEGIN 
    SELECT USER INTO LV_USUARIO FROM DUAL;--OBTENIENDO EL USUARIO DESDE EL SISTEMAS
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;--OBTENER FECHA DESDE EL SISTEMA
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;--OBTENER UN ID VALIDO
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT,ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO
    ,MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
    
    VALUES(LV_ID_BIT,:NEW.ID_COMPU,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO,
    NULL,NULL,0,NULL,0,LV_USUARIO,LV_FECHA,'INSERT');
END TR_I_COMPUTADORA;
/    

SELECT SYSDATE FROM DUAL;
--CAMBIAR EL FORMATO DE MI FECHA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YY HH24:MI:SS';

--PRUEBAS
SELECT * FROM COMPUTADORA;

SELECT * FROM BIT_COMPUTADORA;

--AGREGAR UN REGISTRO INTO 
INSERT INTO COMPUTADORA VALUES(1,'HP','PAVILON',16,'INTEL CORE 19 12TH',15000);
INSERT INTO COMPUTADORA VALUES(2,'DELL','LOL',8,'INTEL CORE 18 12TH',13000);

INSERT INTO COMPUTADORA VALUES(3,'APPLE','MACBOOK AIR',16,'INTEL CORE !9',12000);

--TRIGGER SIMPLE PARA UPDATE
CREATE OR REPLACE TRIGGER TR_U_COMPUTADORA
AFTER UPDATE ON COMPUTADORA
FOR EACH ROW 
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FECHA DATE;
BEGIN 
    SELECT USER INTO LV_USUARIO FROM DUAL;--OBTENIENDO EL USUARIO DESDE EL SISTEMAS
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;--OBTENER FECHA DESDE EL SISTEMA
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;--OBTENER UN ID VALIDO
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT,ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO
    ,MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
    
    VALUES(LV_ID_BIT,:NEW.ID_COMPU,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO,
    :OLD.MARCA,:OLD.MODELO,:OLD.RAM,:OLD.PROCESADOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'UPDATE');
END TR_U_COMPUTADORA;
/    
UPDATE COMPUTADORA SET 
                    MARCA = 'DELL',
                    MODELO = 'LATITUDE',
                    RAM = 10,
                    PROCESADOR = 'AMD RADEON',
                    PRECIO = 14000
                WHERE ID_COMPU = 3;
                
--TRIGGER ELIMINAR
CREATE OR REPLACE TRIGGER TR_D_COMPUTADORA
AFTER DELETE ON COMPUTADORA
FOR EACH ROW 
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FECHA DATE;
BEGIN 
    SELECT USER INTO LV_USUARIO FROM DUAL;--OBTENIENDO EL USUARIO DESDE EL SISTEMAS
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;--OBTENER FECHA DESDE EL SISTEMA
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;--OBTENER UN ID VALIDO
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT,ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO
    ,MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
    
    VALUES(LV_ID_BIT,:OLD.ID_COMPU,NULL,NULL,0,NULL,0,
    :OLD.MARCA,:OLD.MODELO,:OLD.RAM,:OLD.PROCESADOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'DELETE');
END TR_D_COMPUTADORA;
/ 

DELETE FROM COMPUTADORA WHERE ID_COMPU = 3;

SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;

