CREATE TABLE PERSONA(
    ID_PERSONA NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO_P NVARCHAR2(100),
    APELLIDO_M NVARCHAR2(100),
    EDAD NUMBER,
    CORREO NVARCHAR2(100),
    CONSTRAINT PERSONA_PK PRIMARY KEY(ID_PERSONA)
);

COMMIT;

--DDL PARA LA BITACORA DE PERSONA
CREATE TABLE BIT_PERSONA(
    ID_BIT NUMBER,
    
    --VALORES NUEVOS O VALORES :NEW
    ID_PERSONA NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO_P NVARCHAR2(100),
    APELLIDO_M NVARCHAR2(100),
    EDAD NUMBER,
    CORREO NVARCHAR2(100),
    --VALORES ELIMINADOS O VALORES :OLD
    NOMBRE_OLD NVARCHAR2(100),
    APELLIDO_P_OLD NVARCHAR2(100),
    APELLIDO_M_OLD NVARCHAR2(100),
    EDAD_OLD NUMBER,
    CORREO_OLD NVARCHAR2(100),
    
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_PERSONA_PK PRIMARY KEY(ID_BIT)
);

SELECT SYSDATE FROM DUAL;

SELECT * FROM PERSONA;
SELECT * FROM BIT_PERSONA;


--
CREATE OR REPLACE TRIGGER TR_MULTIPLE_PERSONA
AFTER INSERT OR UPDATE OR DELETE ON PERSONA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT S_ID_BIT_PERSONA.NEXTVAL,USER, SYSDATE INTO LV_ID_BIT,LV_USUARIO,LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
    INSERT INTO BIT_PERSONA(ID_BIT,ID_PERSONA,NOMBRE,APELLIDO_P,APELLIDO_M,EDAD,CORREO,
                            NOMBRE_OLD,APELLIDO_P_OLD,APELLIDO_M_OLD,EDAD_OLD,CORREO_OLD,
                            USUARIO,FECHA_MOV,MOVIMIENTO)
                            VALUES(LV_ID_BIT,:NEW.ID_PERSONA,:NEW.NOMBRE,:NEW.APELLIDO_P,:NEW.APELLIDO_M,
                            :NEW.EDAD,:NEW.CORREO,NULL,NULL,NULL,0,NULL,LV_USUARIO,LV_FECHA,'INSERT');
    ELSIF UPDATING THEN 
    INSERT INTO BIT_PERSONA(ID_BIT,ID_PERSONA,NOMBRE,APELLIDO_P,APELLIDO_M,EDAD,CORREO,
                            NOMBRE_OLD,APELLIDO_P_OLD,APELLIDO_M_OLD,EDAD_OLD,CORREO_OLD,
                            USUARIO,FECHA_MOV,MOVIMIENTO)
                            VALUES(LV_ID_BIT,:NEW.ID_PERSONA,:NEW.NOMBRE,:NEW.APELLIDO_P,:NEW.APELLIDO_M,
                            :NEW.EDAD,:NEW.CORREO,:OLD.NOMBRE,:OLD.APELLIDO_P,:OLD.APELLIDO_M,
                            :OLD.EDAD,:OLD.CORREO,LV_USUARIO,LV_FECHA,'UPDATE');
    ELSIF DELETING THEN
    INSERT INTO BIT_PERSONA(ID_BIT,ID_PERSONA,NOMBRE,APELLIDO_P,APELLIDO_M,EDAD,CORREO,
                            NOMBRE_OLD,APELLIDO_P_OLD,APELLIDO_M_OLD,EDAD_OLD,CORREO_OLD,
                            USUARIO,FECHA_MOV,MOVIMIENTO)
                            VALUES(LV_ID_BIT,:OLD.ID_PERSONA,NULL,NULL,NULL,0,NULL,
                            :OLD.NOMBRE,:OLD.APELLIDO_P,:OLD.APELLIDO_M,
                            :OLD.EDAD,:OLD.CORREO,LV_USUARIO,LV_FECHA,'DELETE');
    END IF;
END TR_MULTIPLE_PERSONA;
/

--
INSERT INTO PERSONA VALUES(1,'NORMA','ROMERO','ROMERO',35,'NORMA@GMAIL.COM');
INSERT INTO PERSONA VALUES(2,'MITZY','ZAMUDIO','LIMA',24,'MITZY@GMAIL.COM');
INSERT INTO PERSONA VALUES(3,'ALE','ARREOLA','GARFIAS',30,'ALE@GMAIL.COM');
INSERT INTO PERSONA VALUES(4,'ALEXIS','VARGAS','LLOSA',27,'ALEXIS@GMAIL.COM');
INSERT INTO PERSONA VALUES(5,'PAUL','PEREZ','LOPEZ',40,'PAUL@GMAIL.COM');
INSERT INTO PERSONA VALUES(6,'SONIA','LOPEZ','MENDEZ',15,'SONIA@GMAIL.COM');

--UPDATE
UPDATE PERSONA SET
    NOMBRE='MARLEN'
    /*APELLIDO_P = 'ROMERO',
    APELLIDO_M = 'ROMERO',
    EDAD = 35,
    CORREO = 'NORMA@GMAIL.COM'*/
WHERE ID_PERSONA = 6;

--DELETE
DELETE FROM PERSONA WHERE ID_PERSONA = 6;

SELECT * FROM PERSONA;
SELECT * FROM BIT_PERSONA;