--TRIGGER A NIVEL SENTENCIAS: SE EJECUTA UNA SOLA VEZ POR CADA OPERACION DML

CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    SELECT S_ID_BIT_COMPU.NEXTVAL,USER, SYSDATE INTO LV_ID_BIT,LV_USUARIO,LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    INSERT INTO BIT_COMPUTADORA(ID_BIT,USUARIO,FECHA_MOV,MOVIMIENTO)
    VALUES(LV_ID_BIT,LV_USUARIO,LV_FECHA,LV_MOV);
END;
/

SELECT USUARIO,FECHA_MOV,MOVIMIENTO FROM BIT_COMPUTADORA;
DELETE FROM COMPUTADORA;
DELETE FROM BIT_COMPUTADORA;
INSERT INTO COMPUTADORA VALUES(20,'HP','PAVILLON',8,'INTEL CORE 10',12000);










