--SECUENCIA PARA COMPUTADORA
--SECUENCIA O SEQUENCE SE EMPLEA PARA GENERAR VALORES ENTEROS SECUENCIALES UNICS Y ASIGNARLOS
--A CAMPOS NUMERICOS. SE UTILIZAN GENERALMN¿ENTE PARA LAS CLAVES PRIMARIAS DE LAS TABLAS
--GARANTIZANDO QUE LOS VALORES NOO SE REPITAN

--CREACION DE SECUENCIA
CREATE SEQUENCE S_ID_BIT_COMPU
START WITH 1
MAXVALUE 9999
MINVALUE 1
NOCYCLE;
/

SELECT S_ID_BIT_COMPU.NEXTVAL FROM DUAL;



