CREATE OR REPLACE TRIGGER TR_I_U_D_PERSONA
AFTER INSERT OR UPDATE OR DELETE ON PERSONA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    SELECT S_ID_BIT_PERSONA.NEXTVAL,USER, SYSDATE INTO LV_ID_BIT,LV_USUARIO,LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    INSERT INTO BIT_PERSONA(ID_BIT,USUARIO,FECHA_MOV,MOVIMIENTO)
    VALUES(LV_ID_BIT,LV_USUARIO,LV_FECHA,LV_MOV);
END;
/

INSERT INTO PERSONA VALUES(1,'NORMA','ROMERO','ROMERO',35,'NORMA@GMAIL.COM');
INSERT INTO PERSONA VALUES(2,'MITZY','ZAMUDIO','LIMA',24,'MITZY@GMAIL.COM');
INSERT INTO PERSONA VALUES(3,'ALE','ARREOLA','GARFIAS',30,'ALE@GMAIL.COM');
INSERT INTO PERSONA VALUES(4,'ALEXIS','VARGAS','LLOSA',27,'ALEXIS@GMAIL.COM');
INSERT INTO PERSONA VALUES(5,'PAUL','PEREZ','LOPEZ',40,'PAUL@GMAIL.COM');


--UPDATE
UPDATE PERSONA SET
    --NOMBRE='MARLEN'
    APELLIDO_P = 'LOPEZ'
    /*APELLIDO_M = 'ROMERO',
    EDAD = 35,
    CORREO = 'NORMA@GMAIL.COM'*/
WHERE ID_PERSONA = 1;

SELECT USUARIO,FECHA_MOV,MOVIMIENTO FROM BIT_PERSONA;
SELECT * FROM PERSONA;
DELETE FROM PERSONA;
DELETE FROM BIT_PERSONA;
INSERT INTO PERSONA VALUES(7,'LUZ','GONZALEZ','AMARO',1,'LUZ@GMIAL.COM');
