--Ejercicio de sistema de gestion de peliculas
--crear tabla pelicula
CREATE TABLE PELICULA(
    ID_PELICULA NUMBER,
    TITULO NVARCHAR2(100),
    GENERO NVARCHAR2(100),
    DURACION NVARCHAR2(100),
    CLASIFICACION NVARCHAR2(100),
    ESTRENO NUMBER
);

--INSERTAR REGISTROS
INSERT INTO PELICULA VALUES(1,'EL ORIGEN','CIENCIA FICCION',148,'B15',2010);
INSERT INTO PELICULA VALUES(2,'COCO','ANIMACION',105,'A',2017);
INSERT INTO PELICULA VALUES(3,'GLADIADOR','ACCION',152,'B15',2000);
INSERT INTO PELICULA VALUES(4,'TITANIC','ROMANCE',195,'B',1997);
INSERT INTO PELICULA VALUES(5,'AVENGERS: ENDGAME','SUPERHEROES',181,'B15',2019);
INSERT INTO PELICULA VALUES(6,'LA LA LAND','MUSICAL',128,'B',2016);

SELECT * FROM PELICULA;


--CONSULTAS PRACTICAS
--1.MOSTRAR TODAS LAS PELICULAS
SELECT * FROM PELICULA;


--2.MOSTRAR LAS PELICULAS ESTRENADAS DESPUES DEL 2010
SELECT * FROM PELICULA WHERE ESTRENO > 2010;

--3.MOSTRAR OELICULAS CLASIFICADAS COMO A
SELECT * FROM PELICULA WHERE CLASIFICACION = 'A';

--4.PELICULAS CON DURACION MAYOR A 150 MINUTOS
SELECT * FROM PELICULA WHERE DURACION > 150;

--5.PELICULAS CUYO TITULO CONTIENE LA LETRA A
SELECT * FROM PELICULA WHERE TITULO LIKE '%A%';

--6.DURACION PROMEDIO DE TODAS LAS PELICULAS (REDOONDEADA A 2 DECIMALES)
SELECT ROUND(AVG(DURACION),2) AS TOTAL_DURACION FROM PELICULA;

--7.NUMERO TOTAL DE PELICULAS POR GENERO
/*SELECT CATEGORIA, COUNT(ID_PRODUCTO) AS NO_PRODUCTOS FROM PRODUCTO 
WHERE CATEGORIA IS NOT NULL GROUP BY CATEGORIA;*/
SELECT GENERO, COUNT(ID_PELICULA) AS NO_PELICULAS FROM PELICULA
WHERE GENERO IS NOT NULL GROUP BY GENERO;

--8.PELICULA MAS LARGA
SELECT * FROM PELICULA WHERE DURACION =(
    SELECT MAX(DURACION)
    FROM PELICULA
);

--9.CONCATENAR TITULO Y ESTRENO
SELECT 'TITULO:' || ' ' || TITULO || ' ' || 'ESTRENO:' || ' ' || ESTRENO AS DETALLE FROM PELICULA;

--10.DURACION MAXIMA DE UNA PELICULA
SELECT * FROM PELICULA WHERE DURACION =(
    SELECT MAX(DURACION)
    FROM PELICULA
);

--11.DURACION MINIMA DE UNA PELICULA
SELECT * FROM PELICULA WHERE DURACION =(
    SELECT MIN(DURACION)
    FROM PELICULA
);

--12.ESTRENO MAS ANTIGUO
SELECT * FROM PELICULA WHERE ESTRENO =(
    SELECT MIN(ESTRENO)
    FROM PELICULA
);

--13. SUMA DE TODAS LAS DURACIONES DE PELICULAS
SELECT SUM(DURACION) AS TOTAL_DURACION FROM PELICULA;

--14.DURACIOON PROMEDIO POR CLASIFICACION
/*SELECT GENERO, COUNT(ID_PELICULA) AS NO_PELICULAS FROM PELICULA
WHERE GENERO IS NOT NULL GROUP BY GENERO;*/
SELECT CLASIFICACION, ROUND(AVG(DURACION),2) AS TOTAL FROM PELICULA GROUP BY CLASIFICACION;

--15.PELICULAS QUE DURAN IGUAL QUE LA DURACION DEL PROMEDIO
SELECT * FROM PELICULA
WHERE DURACION = (
    SELECT ROUND(AVG(DURACION))
    FROM PELICULA
);


--16. PELICULA MAS RECIENTE
SELECT * FROM PELICULA WHERE ESTRENO =(
    SELECT MAX(ESTRENO)
    FROM PELICULA
);

--17. PELICULAS MAS CORTAS QUE LAS MAS LARGA
SELECT * FROM PELICULA 
WHERE DURACION < (
    SELECT MAX(DURACION)
    FROM PELICULA
);

--18.PELICULAS CON LA MISMA CLASIFICACION QUE COCO
SELECT * FROM PELICULA 
WHERE CLASIFICACION = (
    SELECT CLASIFICACION
    FROM PELICULA
    WHERE  CLASIFICACION= 'A'
);


--19.CONCATENAR EL TITULO Y CLASIFICACIOON EN UNA COLUMNA TIPO DETALLE 
--(LA PELICULA MATILDA ES DE CLASIFICACIOON A)
SELECT 'LA PELICULA:'|| ' ' || TITULO||' '||'ES DE CLASIFICACION:'||' '||CLASIFICACION 
AS DETALLE FROM PELICULA;

--20.MOSTRAR LA DURACION COMO TEXTO CON UNIDADES (MATILDA DURA 152 MINUTOS)
--SELECT TO_CHAR(AVG(STOCK),'999,999') AS STOCKF FROM PRODUCTO;
SELECT TITULO || ' '||'DURA'||' '||TO_CHAR(DURACION,'999')||' ' || 'MINUTOS' FROM PELICULA;

--21.TRANSFORMAR EL ESTRENO EN ANIO COMOO TEXTO A MENSAJES (MATILDA SE ESTRENO EN EL ANIO 2000)
SELECT TITULO || ' '||'SE ESTRENO EN EL ANIO'||' '||ESTRENO FROM PELICULA;

--22.PELIUCLAS DE ACCION O CIENCIA FICCION CON DURACION MAYOR A 140 MINUTOS

SELECT * FROM PELICULA
WHERE (GENERO = 'ACCION' OR GENERO = 'CIENCIA FICCION') AND DURACION > 140;

--23.PELICULAS QUE NO SON DE ANIMACION NI MUSICAL
SELECT * FROM PELICULA
WHERE GENERO != 'ANIMACION' AND GENERO != 'MUSICAL';

--24. PELICULAS ESTRENADAS ENTRE 2000 Y 2015
SELECT * FROM PELICULA WHERE ESTRENO BETWEEN 2000 AND 2015;

--QUE PELICULAS CUMPLEN CON MAS DE UNA COONDICION
--P/E DURACION > 10 Y CLASIFICACION B15


--QUE CREES QUE ES EL GENERO MAS FRECUENTE
--NINGUNO
SELECT GENERO, COUNT(*) AS TOTAL FROM PELICULA
GROUP BY GENERO
ORDER BY TOTAL DESC;

--QUE PATRON TIENEN LOS TITULOS DE LAS PELICULAS QUE CONTIENE LA LETRA A

SELECT TITULO, 'Contiene A' AS patron FROM  PELICULA
WHERE TITULO LIKE '%A%';