--AGREGAR REGISTROS A TABLA EMPLEADO

INSERT INTO EMPLEADO VALUES(1,'JULIAN','DIAZ',36,'PROGRAMADOR JAVA','TI');
INSERT INTO EMPLEADO VALUES(2,'KAREN','DELGADO',27,'ABOGADA','DERECHO');
INSERT INTO EMPLEADO VALUES(3,'LUCY','ROMERO',29,'TESTER','DEPARTAMENTO DE SISTEMAS');
INSERT INTO EMPLEADO VALUES(4,'MARIO','MORALES',36,'AUXILIAR ADMINISTRATIVO','RH');
INSERT INTO EMPLEADO VALUES(5,'XIMENA','GONZALES',33,'ENCARGADA DE SERVICIOS LEGALES','JURISDICCION');
INSERT INTO EMPLEADO VALUES(6,'JUAN','MARTINEZ',29,'TECNICO EN MANTENIMIENTO','TI');

SELECT * FROM EMPLEADO;

--FUNCIONES DE AGREGACION
--MODIFICAR O CAMBIAR EL NOOMBRE DE LA COLUMNA
ALTER TABLE EMPLEADO RENAME COLUMN APELLIDO_P TO APELLIDO_PATERNO;

--DML ACTUALIZAR
UPDATE EMPLEADO SET NOMBRE = 'ALEJANDRA' WHERE ID_EMPLEADO = 3;

--ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;
--
--BUSQUEDA DE INFORMACION CON CARACTERES ESPECIFICOS 
--BUSCAR EMPLEADOS QUE EMPIEZAN CON LA LETRA A
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'A%';

--BUSCAR EMPLEADOS QUE SU NOMBRE COTENGA LA LETRA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';
--TERMINE CON LA LETRA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--BUSCAR EMPLEADOS QUE SU NOMBRE NO NULL
SELECT * FROM EMPLEADO WHERE NOMBRE IS NOT NULL;

--USO DE LA TABLA DUAL //ES UNA TABLA ESPECIAL EN BASES DE DATOS ORACLE,
--SE UTILIZA PARA SELECCIONES, VALORES LITERALES Y REALIZAR PERACIOONES QUE NO INVLUCRAN TABLAS REALES
-- LA TABLA DUAL CONTIENE UNICAMENTE UNA FILA Y UNA UNICA COLUMNA

SELECT 5 + 5 AS SUMA FROM DUAL;

--FUNCIONES Y CLAUSULAS
--USO DE LA FUNCION LENGHT
SELECT LENGTH('ESTA CADENA ES UNA PRUEBA PARA EL US DE LENGTH') AS TAMANIO FROM DUAL;

--BUSCAR CON MAS CNDICIONES 
-- BUSCAR EMPLEADOS QUE SEAN MAYOR A 25

SELECT * FROM EMPLEADO WHERE EDAD > 25;

SELECT * FROM EMPLEADO WHERE EDAD < 35 ORDER BY EDAD ASC;

--BUSCAR QUE SEAN MAYORES DE 24 Y MENORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD < 30;

--RANGO --> BETWWEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 30;

--BUSQUEDA DE LOS EMPLEADOS CON EL ID 1,2,3,5
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 2 OR ID_EMPLEADO = 3 OR ID_EMPLEADO = 5;
--USO DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,3,5);

--USO DE LA FUNCION GROUP BY Y COUNT 
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;

SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADOS FROM EMPLEADO 
WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

--CONTAR LOS EMPLEADOS QUE TENGAN MAS DE 30
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD > 30;

--FUNCIOS DE AGREGACION SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO WHERE APELLIDO_PATERNO LIKE '%A%';

--FUNCION DE AGREGACION  MAX
SELECT MAX(EDAD) AS EDAD_MAXIMA FROM EMPLEADO;
--MIN
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;

--USO DE LA FUNCION AVG
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;

--USO DE LA FUNCION ROUND
SELECT ROUND(AVG(EDAD),2) AS EDAD_PROMEDIO FROM EMPLEADO;


--USO DE TO CHAR CON FORMATO
SELECT TO_CHAR(AVG(EDAD), 'fm999.0') AS PROMEDIO_EDAD FROM EMPLEADO;

--DALR UN FORMATO DIFEREBTE
--FUNCION CONCAT
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO',' '),NOMBRE), ' '),APELLIDO_PATERNO)
AS DETALLE FROM EMPLEADO;

--CONCATENACION USANDO PIPES O BARRA LATERAL --> ||
SELECT 'EL EMPLEADO (A) ' || NOMBRE || ' ' || APELLIDO_PATERNO || ' DE EDAD '||EDAD ||
' ANIOS, TRABAJA EN EL DEPARTAMENTO DE: ' || DEPARTAMENTO || ' COMO:' || PUESTO AS DETALLLE FROM EMPLEADO;

--SUB COONSULTAS
SELECT * FROM EMPLEADO WHERE
EDAD = (
    SELECT MIN(EDAD)
    FROM EMPLEADO
    WHERE DEPARTAMENTO = 'RH'
);

---
SELECT * FROM EMPLEADO WHERE
EDAD = (
    SELECT MAX(EDAD)
    FROM EMPLEADO
    WHERE DEPARTAMENTO = ('RH')
    ) AND DEPARTAMENTO = 'RH';